BEGIN;
 
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS fonts;
DROP TABLE IF EXISTS vk_sessions;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
 
DROP TYPE IF EXISTS session_auth_type;
DROP TYPE IF EXISTS user_role;
 
COMMIT;