// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/mock_repository.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/bboykiv/topsigner/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockUserRepository) Get(ctx context.Context, filter *model.UserFilter) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filter)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserRepositoryMockRecorder) Get(ctx, filter any) *MockUserRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserRepository)(nil).Get), ctx, filter)
	return &MockUserRepositoryGetCall{Call: call}
}

// MockUserRepositoryGetCall wrap *gomock.Call
type MockUserRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryGetCall) Return(arg0 *model.User, arg1 error) *MockUserRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryGetCall) Do(f func(context.Context, *model.UserFilter) (*model.User, error)) *MockUserRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryGetCall) DoAndReturn(f func(context.Context, *model.UserFilter) (*model.User, error)) *MockUserRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, session *model.Session) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, session any) *MockSessionRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, session)
	return &MockSessionRepositoryCreateCall{Call: call}
}

// MockSessionRepositoryCreateCall wrap *gomock.Call
type MockSessionRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryCreateCall) Return(arg0 *model.Session, arg1 error) *MockSessionRepositoryCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryCreateCall) Do(f func(context.Context, *model.Session) (*model.Session, error)) *MockSessionRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryCreateCall) DoAndReturn(f func(context.Context, *model.Session) (*model.Session, error)) *MockSessionRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockSessionRepository) Delete(ctx context.Context, filter *model.SessionFilter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionRepositoryMockRecorder) Delete(ctx, filter any) *MockSessionRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionRepository)(nil).Delete), ctx, filter)
	return &MockSessionRepositoryDeleteCall{Call: call}
}

// MockSessionRepositoryDeleteCall wrap *gomock.Call
type MockSessionRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryDeleteCall) Return(arg0 error) *MockSessionRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryDeleteCall) Do(f func(context.Context, *model.SessionFilter) error) *MockSessionRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryDeleteCall) DoAndReturn(f func(context.Context, *model.SessionFilter) error) *MockSessionRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockSessionRepository) Get(ctx context.Context, filter *model.SessionFilter) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filter)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionRepositoryMockRecorder) Get(ctx, filter any) *MockSessionRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionRepository)(nil).Get), ctx, filter)
	return &MockSessionRepositoryGetCall{Call: call}
}

// MockSessionRepositoryGetCall wrap *gomock.Call
type MockSessionRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryGetCall) Return(arg0 *model.Session, arg1 error) *MockSessionRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryGetCall) Do(f func(context.Context, *model.SessionFilter) (*model.Session, error)) *MockSessionRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryGetCall) DoAndReturn(f func(context.Context, *model.SessionFilter) (*model.Session, error)) *MockSessionRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockSessionRepository) Update(ctx context.Context, session *model.Session) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, session)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSessionRepositoryMockRecorder) Update(ctx, session any) *MockSessionRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSessionRepository)(nil).Update), ctx, session)
	return &MockSessionRepositoryUpdateCall{Call: call}
}

// MockSessionRepositoryUpdateCall wrap *gomock.Call
type MockSessionRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryUpdateCall) Return(arg0 *model.Session, arg1 error) *MockSessionRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryUpdateCall) Do(f func(context.Context, *model.Session) (*model.Session, error)) *MockSessionRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryUpdateCall) DoAndReturn(f func(context.Context, *model.Session) (*model.Session, error)) *MockSessionRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockVKIDClient is a mock of VKIDClient interface.
type MockVKIDClient struct {
	ctrl     *gomock.Controller
	recorder *MockVKIDClientMockRecorder
	isgomock struct{}
}

// MockVKIDClientMockRecorder is the mock recorder for MockVKIDClient.
type MockVKIDClientMockRecorder struct {
	mock *MockVKIDClient
}

// NewMockVKIDClient creates a new mock instance.
func NewMockVKIDClient(ctrl *gomock.Controller) *MockVKIDClient {
	mock := &MockVKIDClient{ctrl: ctrl}
	mock.recorder = &MockVKIDClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVKIDClient) EXPECT() *MockVKIDClientMockRecorder {
	return m.recorder
}

// GenerateAuthorizationURL mocks base method.
func (m *MockVKIDClient) GenerateAuthorizationURL(challenge, state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAuthorizationURL", challenge, state)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateAuthorizationURL indicates an expected call of GenerateAuthorizationURL.
func (mr *MockVKIDClientMockRecorder) GenerateAuthorizationURL(challenge, state any) *MockVKIDClientGenerateAuthorizationURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAuthorizationURL", reflect.TypeOf((*MockVKIDClient)(nil).GenerateAuthorizationURL), challenge, state)
	return &MockVKIDClientGenerateAuthorizationURLCall{Call: call}
}

// MockVKIDClientGenerateAuthorizationURLCall wrap *gomock.Call
type MockVKIDClientGenerateAuthorizationURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVKIDClientGenerateAuthorizationURLCall) Return(arg0 string) *MockVKIDClientGenerateAuthorizationURLCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVKIDClientGenerateAuthorizationURLCall) Do(f func(string, string) string) *MockVKIDClientGenerateAuthorizationURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVKIDClientGenerateAuthorizationURLCall) DoAndReturn(f func(string, string) string) *MockVKIDClientGenerateAuthorizationURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
