// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/mock_repository.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabaseChecker is a mock of DatabaseChecker interface.
type MockDatabaseChecker struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseCheckerMockRecorder
	isgomock struct{}
}

// MockDatabaseCheckerMockRecorder is the mock recorder for MockDatabaseChecker.
type MockDatabaseCheckerMockRecorder struct {
	mock *MockDatabaseChecker
}

// NewMockDatabaseChecker creates a new mock instance.
func NewMockDatabaseChecker(ctrl *gomock.Controller) *MockDatabaseChecker {
	mock := &MockDatabaseChecker{ctrl: ctrl}
	mock.recorder = &MockDatabaseCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseChecker) EXPECT() *MockDatabaseCheckerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockDatabaseChecker) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockDatabaseCheckerMockRecorder) Ping(ctx any) *MockDatabaseCheckerPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockDatabaseChecker)(nil).Ping), ctx)
	return &MockDatabaseCheckerPingCall{Call: call}
}

// MockDatabaseCheckerPingCall wrap *gomock.Call
type MockDatabaseCheckerPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDatabaseCheckerPingCall) Return(arg0 error) *MockDatabaseCheckerPingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDatabaseCheckerPingCall) Do(f func(context.Context) error) *MockDatabaseCheckerPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDatabaseCheckerPingCall) DoAndReturn(f func(context.Context) error) *MockDatabaseCheckerPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockStorageChecker is a mock of StorageChecker interface.
type MockStorageChecker struct {
	ctrl     *gomock.Controller
	recorder *MockStorageCheckerMockRecorder
	isgomock struct{}
}

// MockStorageCheckerMockRecorder is the mock recorder for MockStorageChecker.
type MockStorageCheckerMockRecorder struct {
	mock *MockStorageChecker
}

// NewMockStorageChecker creates a new mock instance.
func NewMockStorageChecker(ctrl *gomock.Controller) *MockStorageChecker {
	mock := &MockStorageChecker{ctrl: ctrl}
	mock.recorder = &MockStorageCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageChecker) EXPECT() *MockStorageCheckerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockStorageChecker) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockStorageCheckerMockRecorder) Ping(ctx any) *MockStorageCheckerPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockStorageChecker)(nil).Ping), ctx)
	return &MockStorageCheckerPingCall{Call: call}
}

// MockStorageCheckerPingCall wrap *gomock.Call
type MockStorageCheckerPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStorageCheckerPingCall) Return(arg0 error) *MockStorageCheckerPingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStorageCheckerPingCall) Do(f func(context.Context) error) *MockStorageCheckerPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStorageCheckerPingCall) DoAndReturn(f func(context.Context) error) *MockStorageCheckerPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCacheChecker is a mock of CacheChecker interface.
type MockCacheChecker struct {
	ctrl     *gomock.Controller
	recorder *MockCacheCheckerMockRecorder
	isgomock struct{}
}

// MockCacheCheckerMockRecorder is the mock recorder for MockCacheChecker.
type MockCacheCheckerMockRecorder struct {
	mock *MockCacheChecker
}

// NewMockCacheChecker creates a new mock instance.
func NewMockCacheChecker(ctrl *gomock.Controller) *MockCacheChecker {
	mock := &MockCacheChecker{ctrl: ctrl}
	mock.recorder = &MockCacheCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheChecker) EXPECT() *MockCacheCheckerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockCacheChecker) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockCacheCheckerMockRecorder) Ping(ctx any) *MockCacheCheckerPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockCacheChecker)(nil).Ping), ctx)
	return &MockCacheCheckerPingCall{Call: call}
}

// MockCacheCheckerPingCall wrap *gomock.Call
type MockCacheCheckerPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCacheCheckerPingCall) Return(arg0 error) *MockCacheCheckerPingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCacheCheckerPingCall) Do(f func(context.Context) error) *MockCacheCheckerPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCacheCheckerPingCall) DoAndReturn(f func(context.Context) error) *MockCacheCheckerPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
