// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/mock_repository.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/bboykiv/topsigner/internal/model"
	auth "github.com/bboykiv/topsigner/internal/service/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *model.User) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *MockUserRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
	return &MockUserRepositoryCreateCall{Call: call}
}

// MockUserRepositoryCreateCall wrap *gomock.Call
type MockUserRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryCreateCall) Return(arg0 *model.User, arg1 error) *MockUserRepositoryCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryCreateCall) Do(f func(context.Context, *model.User) (*model.User, error)) *MockUserRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryCreateCall) DoAndReturn(f func(context.Context, *model.User) (*model.User, error)) *MockUserRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockUserRepository) Get(ctx context.Context, filter *model.UserFilter) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filter)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserRepositoryMockRecorder) Get(ctx, filter any) *MockUserRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserRepository)(nil).Get), ctx, filter)
	return &MockUserRepositoryGetCall{Call: call}
}

// MockUserRepositoryGetCall wrap *gomock.Call
type MockUserRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryGetCall) Return(arg0 *model.User, arg1 error) *MockUserRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryGetCall) Do(f func(context.Context, *model.UserFilter) (*model.User, error)) *MockUserRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryGetCall) DoAndReturn(f func(context.Context, *model.UserFilter) (*model.User, error)) *MockUserRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, session *model.Session) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, session any) *MockSessionRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, session)
	return &MockSessionRepositoryCreateCall{Call: call}
}

// MockSessionRepositoryCreateCall wrap *gomock.Call
type MockSessionRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryCreateCall) Return(arg0 *model.Session, arg1 error) *MockSessionRepositoryCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryCreateCall) Do(f func(context.Context, *model.Session) (*model.Session, error)) *MockSessionRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryCreateCall) DoAndReturn(f func(context.Context, *model.Session) (*model.Session, error)) *MockSessionRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockSessionRepository) Delete(ctx context.Context, filter *model.SessionFilter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionRepositoryMockRecorder) Delete(ctx, filter any) *MockSessionRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionRepository)(nil).Delete), ctx, filter)
	return &MockSessionRepositoryDeleteCall{Call: call}
}

// MockSessionRepositoryDeleteCall wrap *gomock.Call
type MockSessionRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryDeleteCall) Return(arg0 error) *MockSessionRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryDeleteCall) Do(f func(context.Context, *model.SessionFilter) error) *MockSessionRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryDeleteCall) DoAndReturn(f func(context.Context, *model.SessionFilter) error) *MockSessionRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockSessionRepository) Get(ctx context.Context, filter *model.SessionFilter) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filter)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionRepositoryMockRecorder) Get(ctx, filter any) *MockSessionRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionRepository)(nil).Get), ctx, filter)
	return &MockSessionRepositoryGetCall{Call: call}
}

// MockSessionRepositoryGetCall wrap *gomock.Call
type MockSessionRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryGetCall) Return(arg0 *model.Session, arg1 error) *MockSessionRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryGetCall) Do(f func(context.Context, *model.SessionFilter) (*model.Session, error)) *MockSessionRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryGetCall) DoAndReturn(f func(context.Context, *model.SessionFilter) (*model.Session, error)) *MockSessionRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockSessionRepository) List(ctx context.Context, query *model.SessionQuery) ([]*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, query)
	ret0, _ := ret[0].([]*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSessionRepositoryMockRecorder) List(ctx, query any) *MockSessionRepositoryListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSessionRepository)(nil).List), ctx, query)
	return &MockSessionRepositoryListCall{Call: call}
}

// MockSessionRepositoryListCall wrap *gomock.Call
type MockSessionRepositoryListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryListCall) Return(arg0 []*model.Session, arg1 error) *MockSessionRepositoryListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryListCall) Do(f func(context.Context, *model.SessionQuery) ([]*model.Session, error)) *MockSessionRepositoryListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryListCall) DoAndReturn(f func(context.Context, *model.SessionQuery) ([]*model.Session, error)) *MockSessionRepositoryListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockSessionRepository) Update(ctx context.Context, session *model.Session) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, session)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSessionRepositoryMockRecorder) Update(ctx, session any) *MockSessionRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSessionRepository)(nil).Update), ctx, session)
	return &MockSessionRepositoryUpdateCall{Call: call}
}

// MockSessionRepositoryUpdateCall wrap *gomock.Call
type MockSessionRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryUpdateCall) Return(arg0 *model.Session, arg1 error) *MockSessionRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryUpdateCall) Do(f func(context.Context, *model.Session) (*model.Session, error)) *MockSessionRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryUpdateCall) DoAndReturn(f func(context.Context, *model.Session) (*model.Session, error)) *MockSessionRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCodeVerifierStorage is a mock of CodeVerifierStorage interface.
type MockCodeVerifierStorage struct {
	ctrl     *gomock.Controller
	recorder *MockCodeVerifierStorageMockRecorder
	isgomock struct{}
}

// MockCodeVerifierStorageMockRecorder is the mock recorder for MockCodeVerifierStorage.
type MockCodeVerifierStorageMockRecorder struct {
	mock *MockCodeVerifierStorage
}

// NewMockCodeVerifierStorage creates a new mock instance.
func NewMockCodeVerifierStorage(ctrl *gomock.Controller) *MockCodeVerifierStorage {
	mock := &MockCodeVerifierStorage{ctrl: ctrl}
	mock.recorder = &MockCodeVerifierStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeVerifierStorage) EXPECT() *MockCodeVerifierStorageMockRecorder {
	return m.recorder
}

// Pop mocks base method.
func (m *MockCodeVerifierStorage) Pop(ctx context.Context, state string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pop", ctx, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pop indicates an expected call of Pop.
func (mr *MockCodeVerifierStorageMockRecorder) Pop(ctx, state any) *MockCodeVerifierStoragePopCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pop", reflect.TypeOf((*MockCodeVerifierStorage)(nil).Pop), ctx, state)
	return &MockCodeVerifierStoragePopCall{Call: call}
}

// MockCodeVerifierStoragePopCall wrap *gomock.Call
type MockCodeVerifierStoragePopCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeVerifierStoragePopCall) Return(arg0 string, arg1 error) *MockCodeVerifierStoragePopCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeVerifierStoragePopCall) Do(f func(context.Context, string) (string, error)) *MockCodeVerifierStoragePopCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeVerifierStoragePopCall) DoAndReturn(f func(context.Context, string) (string, error)) *MockCodeVerifierStoragePopCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Set mocks base method.
func (m *MockCodeVerifierStorage) Set(ctx context.Context, state, verifier string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, state, verifier, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCodeVerifierStorageMockRecorder) Set(ctx, state, verifier, ttl any) *MockCodeVerifierStorageSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCodeVerifierStorage)(nil).Set), ctx, state, verifier, ttl)
	return &MockCodeVerifierStorageSetCall{Call: call}
}

// MockCodeVerifierStorageSetCall wrap *gomock.Call
type MockCodeVerifierStorageSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeVerifierStorageSetCall) Return(arg0 error) *MockCodeVerifierStorageSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeVerifierStorageSetCall) Do(f func(context.Context, string, string, time.Duration) error) *MockCodeVerifierStorageSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeVerifierStorageSetCall) DoAndReturn(f func(context.Context, string, string, time.Duration) error) *MockCodeVerifierStorageSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockUserCache is a mock of UserCache interface.
type MockUserCache struct {
	ctrl     *gomock.Controller
	recorder *MockUserCacheMockRecorder
	isgomock struct{}
}

// MockUserCacheMockRecorder is the mock recorder for MockUserCache.
type MockUserCacheMockRecorder struct {
	mock *MockUserCache
}

// NewMockUserCache creates a new mock instance.
func NewMockUserCache(ctrl *gomock.Controller) *MockUserCache {
	mock := &MockUserCache{ctrl: ctrl}
	mock.recorder = &MockUserCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCache) EXPECT() *MockUserCacheMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUserCache) Delete(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserCacheMockRecorder) Delete(ctx, userID any) *MockUserCacheDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserCache)(nil).Delete), ctx, userID)
	return &MockUserCacheDeleteCall{Call: call}
}

// MockUserCacheDeleteCall wrap *gomock.Call
type MockUserCacheDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserCacheDeleteCall) Return(arg0 error) *MockUserCacheDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserCacheDeleteCall) Do(f func(context.Context, int64) error) *MockUserCacheDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserCacheDeleteCall) DoAndReturn(f func(context.Context, int64) error) *MockUserCacheDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockUserCache) Get(ctx context.Context, userID int64) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserCacheMockRecorder) Get(ctx, userID any) *MockUserCacheGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserCache)(nil).Get), ctx, userID)
	return &MockUserCacheGetCall{Call: call}
}

// MockUserCacheGetCall wrap *gomock.Call
type MockUserCacheGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserCacheGetCall) Return(arg0 *model.User, arg1 error) *MockUserCacheGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserCacheGetCall) Do(f func(context.Context, int64) (*model.User, error)) *MockUserCacheGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserCacheGetCall) DoAndReturn(f func(context.Context, int64) (*model.User, error)) *MockUserCacheGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Set mocks base method.
func (m *MockUserCache) Set(ctx context.Context, user *model.User, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, user, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockUserCacheMockRecorder) Set(ctx, user, ttl any) *MockUserCacheSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockUserCache)(nil).Set), ctx, user, ttl)
	return &MockUserCacheSetCall{Call: call}
}

// MockUserCacheSetCall wrap *gomock.Call
type MockUserCacheSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserCacheSetCall) Return(arg0 error) *MockUserCacheSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserCacheSetCall) Do(f func(context.Context, *model.User, time.Duration) error) *MockUserCacheSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserCacheSetCall) DoAndReturn(f func(context.Context, *model.User, time.Duration) error) *MockUserCacheSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockVKIDClient is a mock of VKIDClient interface.
type MockVKIDClient struct {
	ctrl     *gomock.Controller
	recorder *MockVKIDClientMockRecorder
	isgomock struct{}
}

// MockVKIDClientMockRecorder is the mock recorder for MockVKIDClient.
type MockVKIDClientMockRecorder struct {
	mock *MockVKIDClient
}

// NewMockVKIDClient creates a new mock instance.
func NewMockVKIDClient(ctrl *gomock.Controller) *MockVKIDClient {
	mock := &MockVKIDClient{ctrl: ctrl}
	mock.recorder = &MockVKIDClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVKIDClient) EXPECT() *MockVKIDClientMockRecorder {
	return m.recorder
}

// Exchange mocks base method.
func (m *MockVKIDClient) Exchange(ctx context.Context, params *auth.OAuthExchangeTokenParams) (*auth.OAuthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exchange", ctx, params)
	ret0, _ := ret[0].(*auth.OAuthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exchange indicates an expected call of Exchange.
func (mr *MockVKIDClientMockRecorder) Exchange(ctx, params any) *MockVKIDClientExchangeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exchange", reflect.TypeOf((*MockVKIDClient)(nil).Exchange), ctx, params)
	return &MockVKIDClientExchangeCall{Call: call}
}

// MockVKIDClientExchangeCall wrap *gomock.Call
type MockVKIDClientExchangeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVKIDClientExchangeCall) Return(arg0 *auth.OAuthToken, arg1 error) *MockVKIDClientExchangeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVKIDClientExchangeCall) Do(f func(context.Context, *auth.OAuthExchangeTokenParams) (*auth.OAuthToken, error)) *MockVKIDClientExchangeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVKIDClientExchangeCall) DoAndReturn(f func(context.Context, *auth.OAuthExchangeTokenParams) (*auth.OAuthToken, error)) *MockVKIDClientExchangeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAuthorizationURL mocks base method.
func (m *MockVKIDClient) GetAuthorizationURL(codeChallenge, state string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorizationURL", codeChallenge, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorizationURL indicates an expected call of GetAuthorizationURL.
func (mr *MockVKIDClientMockRecorder) GetAuthorizationURL(codeChallenge, state any) *MockVKIDClientGetAuthorizationURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorizationURL", reflect.TypeOf((*MockVKIDClient)(nil).GetAuthorizationURL), codeChallenge, state)
	return &MockVKIDClientGetAuthorizationURLCall{Call: call}
}

// MockVKIDClientGetAuthorizationURLCall wrap *gomock.Call
type MockVKIDClientGetAuthorizationURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVKIDClientGetAuthorizationURLCall) Return(arg0 string, arg1 error) *MockVKIDClientGetAuthorizationURLCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVKIDClientGetAuthorizationURLCall) Do(f func(string, string) (string, error)) *MockVKIDClientGetAuthorizationURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVKIDClientGetAuthorizationURLCall) DoAndReturn(f func(string, string) (string, error)) *MockVKIDClientGetAuthorizationURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Logout mocks base method.
func (m *MockVKIDClient) Logout(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockVKIDClientMockRecorder) Logout(ctx, token any) *MockVKIDClientLogoutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockVKIDClient)(nil).Logout), ctx, token)
	return &MockVKIDClientLogoutCall{Call: call}
}

// MockVKIDClientLogoutCall wrap *gomock.Call
type MockVKIDClientLogoutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVKIDClientLogoutCall) Return(arg0 error) *MockVKIDClientLogoutCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVKIDClientLogoutCall) Do(f func(context.Context, string) error) *MockVKIDClientLogoutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVKIDClientLogoutCall) DoAndReturn(f func(context.Context, string) error) *MockVKIDClientLogoutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Refresh mocks base method.
func (m *MockVKIDClient) Refresh(ctx context.Context, params *auth.OAuthRefreshTokenParams) (*auth.OAuthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, params)
	ret0, _ := ret[0].(*auth.OAuthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockVKIDClientMockRecorder) Refresh(ctx, params any) *MockVKIDClientRefreshCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockVKIDClient)(nil).Refresh), ctx, params)
	return &MockVKIDClientRefreshCall{Call: call}
}

// MockVKIDClientRefreshCall wrap *gomock.Call
type MockVKIDClientRefreshCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVKIDClientRefreshCall) Return(arg0 *auth.OAuthToken, arg1 error) *MockVKIDClientRefreshCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVKIDClientRefreshCall) Do(f func(context.Context, *auth.OAuthRefreshTokenParams) (*auth.OAuthToken, error)) *MockVKIDClientRefreshCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVKIDClientRefreshCall) DoAndReturn(f func(context.Context, *auth.OAuthRefreshTokenParams) (*auth.OAuthToken, error)) *MockVKIDClientRefreshCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
