// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/mock_repository.go -package=mock -typed
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/bboykiv/topsigner/internal/model"
	auth "github.com/bboykiv/topsigner/internal/service/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, user *model.User) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, user any) *MockUserRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, user)
	return &MockUserRepositoryCreateCall{Call: call}
}

// MockUserRepositoryCreateCall wrap *gomock.Call
type MockUserRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryCreateCall) Return(arg0 *model.User, arg1 error) *MockUserRepositoryCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryCreateCall) Do(f func(context.Context, *model.User) (*model.User, error)) *MockUserRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryCreateCall) DoAndReturn(f func(context.Context, *model.User) (*model.User, error)) *MockUserRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockUserRepository) Get(ctx context.Context, filter *model.UserFilter) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filter)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserRepositoryMockRecorder) Get(ctx, filter any) *MockUserRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserRepository)(nil).Get), ctx, filter)
	return &MockUserRepositoryGetCall{Call: call}
}

// MockUserRepositoryGetCall wrap *gomock.Call
type MockUserRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserRepositoryGetCall) Return(arg0 *model.User, arg1 error) *MockUserRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserRepositoryGetCall) Do(f func(context.Context, *model.UserFilter) (*model.User, error)) *MockUserRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserRepositoryGetCall) DoAndReturn(f func(context.Context, *model.UserFilter) (*model.User, error)) *MockUserRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSessionRepository is a mock of SessionRepository interface.
type MockSessionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionRepositoryMockRecorder is the mock recorder for MockSessionRepository.
type MockSessionRepositoryMockRecorder struct {
	mock *MockSessionRepository
}

// NewMockSessionRepository creates a new mock instance.
func NewMockSessionRepository(ctrl *gomock.Controller) *MockSessionRepository {
	mock := &MockSessionRepository{ctrl: ctrl}
	mock.recorder = &MockSessionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepository) EXPECT() *MockSessionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepository) Create(ctx context.Context, session *model.Session) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, session)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepositoryMockRecorder) Create(ctx, session any) *MockSessionRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepository)(nil).Create), ctx, session)
	return &MockSessionRepositoryCreateCall{Call: call}
}

// MockSessionRepositoryCreateCall wrap *gomock.Call
type MockSessionRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryCreateCall) Return(arg0 *model.Session, arg1 error) *MockSessionRepositoryCreateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryCreateCall) Do(f func(context.Context, *model.Session) (*model.Session, error)) *MockSessionRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryCreateCall) DoAndReturn(f func(context.Context, *model.Session) (*model.Session, error)) *MockSessionRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockSessionRepository) Delete(ctx context.Context, filter *model.SessionFilter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, filter)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionRepositoryMockRecorder) Delete(ctx, filter any) *MockSessionRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionRepository)(nil).Delete), ctx, filter)
	return &MockSessionRepositoryDeleteCall{Call: call}
}

// MockSessionRepositoryDeleteCall wrap *gomock.Call
type MockSessionRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryDeleteCall) Return(arg0 error) *MockSessionRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryDeleteCall) Do(f func(context.Context, *model.SessionFilter) error) *MockSessionRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryDeleteCall) DoAndReturn(f func(context.Context, *model.SessionFilter) error) *MockSessionRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockSessionRepository) Get(ctx context.Context, filter *model.SessionFilter) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filter)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionRepositoryMockRecorder) Get(ctx, filter any) *MockSessionRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionRepository)(nil).Get), ctx, filter)
	return &MockSessionRepositoryGetCall{Call: call}
}

// MockSessionRepositoryGetCall wrap *gomock.Call
type MockSessionRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryGetCall) Return(arg0 *model.Session, arg1 error) *MockSessionRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryGetCall) Do(f func(context.Context, *model.SessionFilter) (*model.Session, error)) *MockSessionRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryGetCall) DoAndReturn(f func(context.Context, *model.SessionFilter) (*model.Session, error)) *MockSessionRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockSessionRepository) List(ctx context.Context, query *model.SessionQuery) ([]*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, query)
	ret0, _ := ret[0].([]*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSessionRepositoryMockRecorder) List(ctx, query any) *MockSessionRepositoryListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSessionRepository)(nil).List), ctx, query)
	return &MockSessionRepositoryListCall{Call: call}
}

// MockSessionRepositoryListCall wrap *gomock.Call
type MockSessionRepositoryListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryListCall) Return(arg0 []*model.Session, arg1 error) *MockSessionRepositoryListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryListCall) Do(f func(context.Context, *model.SessionQuery) ([]*model.Session, error)) *MockSessionRepositoryListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryListCall) DoAndReturn(f func(context.Context, *model.SessionQuery) ([]*model.Session, error)) *MockSessionRepositoryListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockSessionRepository) Update(ctx context.Context, session *model.Session) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, session)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSessionRepositoryMockRecorder) Update(ctx, session any) *MockSessionRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSessionRepository)(nil).Update), ctx, session)
	return &MockSessionRepositoryUpdateCall{Call: call}
}

// MockSessionRepositoryUpdateCall wrap *gomock.Call
type MockSessionRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionRepositoryUpdateCall) Return(arg0 *model.Session, arg1 error) *MockSessionRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionRepositoryUpdateCall) Do(f func(context.Context, *model.Session) (*model.Session, error)) *MockSessionRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionRepositoryUpdateCall) DoAndReturn(f func(context.Context, *model.Session) (*model.Session, error)) *MockSessionRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCodeVerifierRepository is a mock of CodeVerifierRepository interface.
type MockCodeVerifierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCodeVerifierRepositoryMockRecorder
	isgomock struct{}
}

// MockCodeVerifierRepositoryMockRecorder is the mock recorder for MockCodeVerifierRepository.
type MockCodeVerifierRepositoryMockRecorder struct {
	mock *MockCodeVerifierRepository
}

// NewMockCodeVerifierRepository creates a new mock instance.
func NewMockCodeVerifierRepository(ctrl *gomock.Controller) *MockCodeVerifierRepository {
	mock := &MockCodeVerifierRepository{ctrl: ctrl}
	mock.recorder = &MockCodeVerifierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeVerifierRepository) EXPECT() *MockCodeVerifierRepositoryMockRecorder {
	return m.recorder
}

// Pop mocks base method.
func (m *MockCodeVerifierRepository) Pop(ctx context.Context, state string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pop", ctx, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pop indicates an expected call of Pop.
func (mr *MockCodeVerifierRepositoryMockRecorder) Pop(ctx, state any) *MockCodeVerifierRepositoryPopCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pop", reflect.TypeOf((*MockCodeVerifierRepository)(nil).Pop), ctx, state)
	return &MockCodeVerifierRepositoryPopCall{Call: call}
}

// MockCodeVerifierRepositoryPopCall wrap *gomock.Call
type MockCodeVerifierRepositoryPopCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeVerifierRepositoryPopCall) Return(arg0 string, arg1 error) *MockCodeVerifierRepositoryPopCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeVerifierRepositoryPopCall) Do(f func(context.Context, string) (string, error)) *MockCodeVerifierRepositoryPopCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeVerifierRepositoryPopCall) DoAndReturn(f func(context.Context, string) (string, error)) *MockCodeVerifierRepositoryPopCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Set mocks base method.
func (m *MockCodeVerifierRepository) Set(ctx context.Context, state, verifier string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, state, verifier, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCodeVerifierRepositoryMockRecorder) Set(ctx, state, verifier, ttl any) *MockCodeVerifierRepositorySetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCodeVerifierRepository)(nil).Set), ctx, state, verifier, ttl)
	return &MockCodeVerifierRepositorySetCall{Call: call}
}

// MockCodeVerifierRepositorySetCall wrap *gomock.Call
type MockCodeVerifierRepositorySetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeVerifierRepositorySetCall) Return(arg0 error) *MockCodeVerifierRepositorySetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeVerifierRepositorySetCall) Do(f func(context.Context, string, string, time.Duration) error) *MockCodeVerifierRepositorySetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeVerifierRepositorySetCall) DoAndReturn(f func(context.Context, string, string, time.Duration) error) *MockCodeVerifierRepositorySetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockUserCacheRepository is a mock of UserCacheRepository interface.
type MockUserCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockUserCacheRepositoryMockRecorder is the mock recorder for MockUserCacheRepository.
type MockUserCacheRepositoryMockRecorder struct {
	mock *MockUserCacheRepository
}

// NewMockUserCacheRepository creates a new mock instance.
func NewMockUserCacheRepository(ctrl *gomock.Controller) *MockUserCacheRepository {
	mock := &MockUserCacheRepository{ctrl: ctrl}
	mock.recorder = &MockUserCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCacheRepository) EXPECT() *MockUserCacheRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUserCacheRepository) Delete(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserCacheRepositoryMockRecorder) Delete(ctx, userID any) *MockUserCacheRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserCacheRepository)(nil).Delete), ctx, userID)
	return &MockUserCacheRepositoryDeleteCall{Call: call}
}

// MockUserCacheRepositoryDeleteCall wrap *gomock.Call
type MockUserCacheRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserCacheRepositoryDeleteCall) Return(arg0 error) *MockUserCacheRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserCacheRepositoryDeleteCall) Do(f func(context.Context, int64) error) *MockUserCacheRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserCacheRepositoryDeleteCall) DoAndReturn(f func(context.Context, int64) error) *MockUserCacheRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockUserCacheRepository) Get(ctx context.Context, userID int64) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserCacheRepositoryMockRecorder) Get(ctx, userID any) *MockUserCacheRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserCacheRepository)(nil).Get), ctx, userID)
	return &MockUserCacheRepositoryGetCall{Call: call}
}

// MockUserCacheRepositoryGetCall wrap *gomock.Call
type MockUserCacheRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserCacheRepositoryGetCall) Return(arg0 *model.User, arg1 error) *MockUserCacheRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserCacheRepositoryGetCall) Do(f func(context.Context, int64) (*model.User, error)) *MockUserCacheRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserCacheRepositoryGetCall) DoAndReturn(f func(context.Context, int64) (*model.User, error)) *MockUserCacheRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Set mocks base method.
func (m *MockUserCacheRepository) Set(ctx context.Context, user *model.User, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, user, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockUserCacheRepositoryMockRecorder) Set(ctx, user, ttl any) *MockUserCacheRepositorySetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockUserCacheRepository)(nil).Set), ctx, user, ttl)
	return &MockUserCacheRepositorySetCall{Call: call}
}

// MockUserCacheRepositorySetCall wrap *gomock.Call
type MockUserCacheRepositorySetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUserCacheRepositorySetCall) Return(arg0 error) *MockUserCacheRepositorySetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUserCacheRepositorySetCall) Do(f func(context.Context, *model.User, time.Duration) error) *MockUserCacheRepositorySetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUserCacheRepositorySetCall) DoAndReturn(f func(context.Context, *model.User, time.Duration) error) *MockUserCacheRepositorySetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSessionCacheRepository is a mock of SessionCacheRepository interface.
type MockSessionCacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCacheRepositoryMockRecorder
	isgomock struct{}
}

// MockSessionCacheRepositoryMockRecorder is the mock recorder for MockSessionCacheRepository.
type MockSessionCacheRepositoryMockRecorder struct {
	mock *MockSessionCacheRepository
}

// NewMockSessionCacheRepository creates a new mock instance.
func NewMockSessionCacheRepository(ctrl *gomock.Controller) *MockSessionCacheRepository {
	mock := &MockSessionCacheRepository{ctrl: ctrl}
	mock.recorder = &MockSessionCacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCacheRepository) EXPECT() *MockSessionCacheRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSessionCacheRepository) Delete(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionCacheRepositoryMockRecorder) Delete(ctx, sessionID any) *MockSessionCacheRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionCacheRepository)(nil).Delete), ctx, sessionID)
	return &MockSessionCacheRepositoryDeleteCall{Call: call}
}

// MockSessionCacheRepositoryDeleteCall wrap *gomock.Call
type MockSessionCacheRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionCacheRepositoryDeleteCall) Return(arg0 error) *MockSessionCacheRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionCacheRepositoryDeleteCall) Do(f func(context.Context, string) error) *MockSessionCacheRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionCacheRepositoryDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockSessionCacheRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockSessionCacheRepository) Get(ctx context.Context, sessionID string) (*model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, sessionID)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionCacheRepositoryMockRecorder) Get(ctx, sessionID any) *MockSessionCacheRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSessionCacheRepository)(nil).Get), ctx, sessionID)
	return &MockSessionCacheRepositoryGetCall{Call: call}
}

// MockSessionCacheRepositoryGetCall wrap *gomock.Call
type MockSessionCacheRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionCacheRepositoryGetCall) Return(arg0 *model.Session, arg1 error) *MockSessionCacheRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionCacheRepositoryGetCall) Do(f func(context.Context, string) (*model.Session, error)) *MockSessionCacheRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionCacheRepositoryGetCall) DoAndReturn(f func(context.Context, string) (*model.Session, error)) *MockSessionCacheRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Set mocks base method.
func (m *MockSessionCacheRepository) Set(ctx context.Context, session *model.Session, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, session, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockSessionCacheRepositoryMockRecorder) Set(ctx, session, ttl any) *MockSessionCacheRepositorySetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSessionCacheRepository)(nil).Set), ctx, session, ttl)
	return &MockSessionCacheRepositorySetCall{Call: call}
}

// MockSessionCacheRepositorySetCall wrap *gomock.Call
type MockSessionCacheRepositorySetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSessionCacheRepositorySetCall) Return(arg0 error) *MockSessionCacheRepositorySetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSessionCacheRepositorySetCall) Do(f func(context.Context, *model.Session, time.Duration) error) *MockSessionCacheRepositorySetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSessionCacheRepositorySetCall) DoAndReturn(f func(context.Context, *model.Session, time.Duration) error) *MockSessionCacheRepositorySetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockVKIDClient is a mock of VKIDClient interface.
type MockVKIDClient struct {
	ctrl     *gomock.Controller
	recorder *MockVKIDClientMockRecorder
	isgomock struct{}
}

// MockVKIDClientMockRecorder is the mock recorder for MockVKIDClient.
type MockVKIDClientMockRecorder struct {
	mock *MockVKIDClient
}

// NewMockVKIDClient creates a new mock instance.
func NewMockVKIDClient(ctrl *gomock.Controller) *MockVKIDClient {
	mock := &MockVKIDClient{ctrl: ctrl}
	mock.recorder = &MockVKIDClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVKIDClient) EXPECT() *MockVKIDClientMockRecorder {
	return m.recorder
}

// ExchangeOAuthToken mocks base method.
func (m *MockVKIDClient) ExchangeOAuthToken(ctx context.Context, params *auth.OAuthExchangeTokenParams) (*auth.OAuthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeOAuthToken", ctx, params)
	ret0, _ := ret[0].(*auth.OAuthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeOAuthToken indicates an expected call of ExchangeOAuthToken.
func (mr *MockVKIDClientMockRecorder) ExchangeOAuthToken(ctx, params any) *MockVKIDClientExchangeOAuthTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeOAuthToken", reflect.TypeOf((*MockVKIDClient)(nil).ExchangeOAuthToken), ctx, params)
	return &MockVKIDClientExchangeOAuthTokenCall{Call: call}
}

// MockVKIDClientExchangeOAuthTokenCall wrap *gomock.Call
type MockVKIDClientExchangeOAuthTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVKIDClientExchangeOAuthTokenCall) Return(arg0 *auth.OAuthToken, arg1 error) *MockVKIDClientExchangeOAuthTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVKIDClientExchangeOAuthTokenCall) Do(f func(context.Context, *auth.OAuthExchangeTokenParams) (*auth.OAuthToken, error)) *MockVKIDClientExchangeOAuthTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVKIDClientExchangeOAuthTokenCall) DoAndReturn(f func(context.Context, *auth.OAuthExchangeTokenParams) (*auth.OAuthToken, error)) *MockVKIDClientExchangeOAuthTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GenerateOAuthURL mocks base method.
func (m *MockVKIDClient) GenerateOAuthURL(challenge, state string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateOAuthURL", challenge, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateOAuthURL indicates an expected call of GenerateOAuthURL.
func (mr *MockVKIDClientMockRecorder) GenerateOAuthURL(challenge, state any) *MockVKIDClientGenerateOAuthURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateOAuthURL", reflect.TypeOf((*MockVKIDClient)(nil).GenerateOAuthURL), challenge, state)
	return &MockVKIDClientGenerateOAuthURLCall{Call: call}
}

// MockVKIDClientGenerateOAuthURLCall wrap *gomock.Call
type MockVKIDClientGenerateOAuthURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVKIDClientGenerateOAuthURLCall) Return(arg0 string, arg1 error) *MockVKIDClientGenerateOAuthURLCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVKIDClientGenerateOAuthURLCall) Do(f func(string, string) (string, error)) *MockVKIDClientGenerateOAuthURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVKIDClientGenerateOAuthURLCall) DoAndReturn(f func(string, string) (string, error)) *MockVKIDClientGenerateOAuthURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Logout mocks base method.
func (m *MockVKIDClient) Logout(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockVKIDClientMockRecorder) Logout(ctx, token any) *MockVKIDClientLogoutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockVKIDClient)(nil).Logout), ctx, token)
	return &MockVKIDClientLogoutCall{Call: call}
}

// MockVKIDClientLogoutCall wrap *gomock.Call
type MockVKIDClientLogoutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVKIDClientLogoutCall) Return(arg0 error) *MockVKIDClientLogoutCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVKIDClientLogoutCall) Do(f func(context.Context, string) error) *MockVKIDClientLogoutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVKIDClientLogoutCall) DoAndReturn(f func(context.Context, string) error) *MockVKIDClientLogoutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RefreshOAuthToken mocks base method.
func (m *MockVKIDClient) RefreshOAuthToken(ctx context.Context, params *auth.OAuthRefreshTokenParams) (*auth.OAuthToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshOAuthToken", ctx, params)
	ret0, _ := ret[0].(*auth.OAuthToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshOAuthToken indicates an expected call of RefreshOAuthToken.
func (mr *MockVKIDClientMockRecorder) RefreshOAuthToken(ctx, params any) *MockVKIDClientRefreshOAuthTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshOAuthToken", reflect.TypeOf((*MockVKIDClient)(nil).RefreshOAuthToken), ctx, params)
	return &MockVKIDClientRefreshOAuthTokenCall{Call: call}
}

// MockVKIDClientRefreshOAuthTokenCall wrap *gomock.Call
type MockVKIDClientRefreshOAuthTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockVKIDClientRefreshOAuthTokenCall) Return(arg0 *auth.OAuthToken, arg1 error) *MockVKIDClientRefreshOAuthTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockVKIDClientRefreshOAuthTokenCall) Do(f func(context.Context, *auth.OAuthRefreshTokenParams) (*auth.OAuthToken, error)) *MockVKIDClientRefreshOAuthTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockVKIDClientRefreshOAuthTokenCall) DoAndReturn(f func(context.Context, *auth.OAuthRefreshTokenParams) (*auth.OAuthToken, error)) *MockVKIDClientRefreshOAuthTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
